name: Deploy Snake Game

on:
  push:
    branches:
      - main  # Runs only when changes are pushed to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # ✅ Updated to latest version

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t vishnukbhasker/snake-game:latest -f app/Dockerfile app/
          docker images  # ✅ Verify the built image

      - name: Push Docker Image
        run: docker push vishnukbhasker/snake-game:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 3.80.182.10
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"  # ✅ Ensure login before pulling
            docker pull vishnukbhasker/snake-game:latest
            docker stop snake-game-container || true
            docker rm snake-game-container || true
            docker run -d --name snake-game-container -p 80:80 vishnukbhasker/snake-game:latest
